//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myblog_website.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogerWebsiteEntities : DbContext
    {
        public BlogerWebsiteEntities()
            : base("name=BlogerWebsiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAccount> tblAccounts { get; set; }
        public virtual DbSet<tblAllOfWeb> tblAllOfWebs { get; set; }
        public virtual DbSet<tblBaiViet> tblBaiViets { get; set; }
        public virtual DbSet<tblBV_comment> tblBV_comment { get; set; }
        public virtual DbSet<tblTag> tblTags { get; set; }
        public virtual DbSet<tblTag_BaiViet> tblTag_BaiViet { get; set; }
        public virtual DbSet<tblTHeLoai> tblTHeLoais { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUser_Baiviet> tblUser_Baiviet { get; set; }
    }
}
