//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myblog_website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAllOfWeb
    {
        public int id { get; set; }
        public string slogan { get; set; }
        public string img_Logo { get; set; }
        public string img_Login { get; set; }
        public string link_FanPage_Face { get; set; }
        public string link_FanPage_TW { get; set; }
        public string link_FanPage_IG { get; set; }
    }
}
