//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myblog_website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTag_BaiViet
    {
        public int id_Tag_Baiviet { get; set; }
        public Nullable<int> id_tag { get; set; }
        public Nullable<int> id_BaiViet { get; set; }
    
        public virtual tblBaiViet tblBaiViet { get; set; }
        public virtual tblTag tblTag { get; set; }
    }
}
