//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myblog_website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTHeLoai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTHeLoai()
        {
            this.tblBaiViets = new HashSet<tblBaiViet>();
        }
    
        public int id_theloai { get; set; }
        public string name_TheLoai { get; set; }
        public Nullable<int> soLuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBaiViet> tblBaiViets { get; set; }
    }
}
