//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myblog_website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblUser_Baiviet = new HashSet<tblUser_Baiviet>();
        }
    
        public int id_User { get; set; }
        public Nullable<int> id_acc { get; set; }
        public string name_User { get; set; }
        public string nickName { get; set; }
        public Nullable<System.DateTime> date_Of_Birth { get; set; }
        public string Email { get; set; }
        public string title_User { get; set; }
        public string link_FB { get; set; }
        public string link_IG { get; set; }
        public Nullable<int> sl_BaiViet { get; set; }
        public string avata_img { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUser_Baiviet> tblUser_Baiviet { get; set; }
    }
}
